# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# docs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Directory Listing
description: GitHub Action to generate `index.html` files for directory listings

branding:
  icon: file-plus
  color: blue

inputs:
  target:
    description: Path to the target directory
    default: .
  ignore:
    description: |
      Patterns for ignoring files or directories can be separated by commas or new lines.
      To ignore a directory recursively, please add `/**` at the end of the directory name.

      When a directory is ignored, an index file will not be generated for it, and excluded files will not be listed
      in the index file.

      For more examples, please refer to: https://github.com/isaacs/node-glob#usage
    default: '**/index.html' # eg. node_modules/**,**/*.log
  show-hidden:
    description: Whether to display hidden files and directories
    default: 'false'
  overwrite:
    description: Whether to overwrite existing index.html files
    default: 'false'
  footer:
    description: The footer content to be added to the index file
    default: 'Repository <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>'

outputs:
  generated:
    description: Whether the index files were generated (an array of paths)

runs:
  using: node24
  main: dist/index.js
